force-app/main/default/objects/Timeline_Configuration__c/Timeline_Configuration__c.object-meta.xml
<CustomObject>
    <description>Custom object to allow additional customization for History Timeline component.</description>
    <label>Timeline Configuration</label>
    <nameField>
        <displayFormat>TC{0000}</displayFormat>
        <label>Timeline Configuration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Configuration__c/fields/Config_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Config_Identifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>This value is used to identify configuration for the component. This value should be provided in LIghtning App Builder when configuring the component.</inlineHelpText>
    <label>Config Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Content_Format__c.field-meta.xml
<CustomField>
    <fullName>Content_Format__c</fullName>
    <inlineHelpText>Defines format in which Timeline content is displayed.</inlineHelpText>
    <label>Content Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classic</fullName>
                <default>true</default>
                <label>Classic</label>
            </value>
            <value>
                <fullName>Minimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Default_Date_Filter__c.field-meta.xml
<CustomField>
    <fullName>Default_Date_Filter__c</fullName>
    <inlineHelpText>Default value for Date Filter. This value needs to be either &apos;All Time&apos; or one of the selected values for Visible Date Filters.</inlineHelpText>
    <label>Default Date Filter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Date_Filter_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Primary_Grouping_By__c.field-meta.xml
<CustomField>
    <fullName>Primary_Grouping_By__c</fullName>
    <inlineHelpText>Primary grouping for the timeline content.</inlineHelpText>
    <label>Primary Grouping By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
                <default>true</default>
                <label>Date</label>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Show_Record_Link__c.field-meta.xml
<CustomField>
    <fullName>Show_Record_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Displays a button that navigates to record detail. Useful when displaying the data for related records.</inlineHelpText>
    <label>Show Record Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Show_Table_format_button__c.field-meta.xml
<CustomField>
    <fullName>Show_Table_format_button__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Shows button that navigates to OOB table format. Make sure the standard History Related List is added to the Page Layout.</inlineHelpText>
    <label>Show Table format button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Timeline_Content_Height__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Content_Height__c</fullName>
    <inlineHelpText>Enter height with unit such as px, rem, em, etc. Leave blank to let the timeline expand based on content. This value overrides the value provided in Lightning App builder.</inlineHelpText>
    <label>Timeline Content Height</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/fields/Visible_Date_Filters__c.field-meta.xml
<CustomField>
    <fullName>Visible_Date_Filters__c</fullName>
    <inlineHelpText>List of date filters to show up in the timeline component.</inlineHelpText>
    <label>Visible Date Filters</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Date_Filter_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/recordTypes/History_Config.recordType-meta.xml
<RecordType>
    <fullName>History_Config</fullName>
    <active>true</active>
    <label>History Config</label>
</RecordType>

force-app/main/default/classes/TimelineComponentTest.cls
/*
BSD 3-Clause License
Copyright (c) 2020, Kshitij Lawate (kshitijlawate.com)

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
@isTest
public with sharing class TimelineComponentTest {
    
    @TestSetup 
    static void makeData(){
        Timeline_Configuration__c tcIns1 = new Timeline_Configuration__c(); 
        tcIns1.Config_Identifier__c = 'Field_Grouping';
        tcIns1.Content_Format__c = TimelineProperties.TIMELINE_CONTENT_FORMAT_MINIMAL;
        tcIns1.Default_Date_Filter__c = 'THIS_FISCAL_YEAR+LAST_FISCAL_YEAR';
        tcIns1.Primary_Grouping_By__c = TimelineProperties.PRIMARY_GROUPING_FIELD;
        tcIns1.Show_Record_Link__c = true;
        tcIns1.Show_Table_format_button__c = true;
        tcIns1.Timeline_Content_Height__c = '800px';
        tcIns1.Visible_Date_Filters__c = 'THIS_QUARTER;LAST_MONTH;THIS_FISCAL_YEAR+LAST_FISCAL_YEAR';
        tcIns1.RecordTypeId = Schema.SObjectType.Timeline_Configuration__c.getRecordTypeInfosByDeveloperName().get('History_Config').getRecordTypeId();
        insert tcIns1;
    }
    
    @isTest
    static void timelineTestGroupByDate() 
    {
        List<sObject> lstAccountHistory = Test.loadData(AccountHistory.sObjectType, 'AccountHistory');
        system.debug('lstAccountHistory='+lstAccountHistory);

        TimelineComponentHelper.lstRecordHistory = (List<AccountHistory>) lstAccountHistory;
        ParamWrapper paramWrap = new ParamWrapper(); 
        paramWrap.recordId = (id) lstAccountHistory[0].get('AccountId');
        paramWrap.relationshipFieldAPI = TimelineProperties.ID_FIELD;
        BaseWrapper twIns = TimelineComponentHelper.getSobjectHistory(paramWrap);

        system.debug('twIns=' + twIns);

        system.assertEquals(twIns.historyTrackedRecordId, paramWrap.recordId);
        system.assert(twIns.lstSectionWrapper.size() > 0);
        system.assertEquals(twIns.lstSectionWrapper[0].isDateTime, true);
    }

    @isTest
    static void timelineTestGroupByField() 
    {
        List<sObject> lstAccountHistory = Test.loadData(AccountHistory.sObjectType, 'AccountHistory');

        TimelineComponentHelper.lstRecordHistory = (List<AccountHistory>) lstAccountHistory;
        ParamWrapper paramWrap = new ParamWrapper(); 
        paramWrap.recordId = (id) lstAccountHistory[0].get('AccountId');
        paramWrap.relationshipFieldAPI = TimelineProperties.ID_FIELD;
        paramWrap.timelineConfigName = 'Field_Grouping'; 
        BaseWrapper twIns = TimelineComponentHelper.getSobjectHistory(paramWrap);

        system.assertEquals(twIns.historyTrackedRecordId, (Id)lstAccountHistory[0].get('AccountId'));
        system.assert(twIns.lstSectionWrapper.size() > 0);
        system.assertEquals(twIns.lstSectionWrapper[0].isDateTime, false);
    }

    @isTest
    static void timelineConfigTriggerTest() {
        Timeline_Configuration__c tcQueried = [SELECT Id FROM Timeline_Configuration__c WHERE Config_Identifier__c = 'Field_Grouping' LIMIT 1];
        Test.startTest();
        tcQueried.Default_Date_Filter__c = 'LAST_WEEK';

        try {
            update tcQueried;
        }
        catch (exception ex) {
            system.assert(ex.getMessage().contains(System.Label.MsgError_TimelineConfigDefaultFilter));
        }
        Test.stopTest();
    }
}